SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DinosaurOccurrences'
ORDER BY ORDINAL_POSITION;

ALTER TABLE dbo.DinosaurOccurrences
DROP COLUMN country;

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN (
    'DinosaurOccurrences',
    'pbdb_dinosaur_occurrences_clean'
);

SELECT 
    ORDINAL_POSITION,
    COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DinosaurOccurrences'
ORDER BY ORDINAL_POSITION;